"""Remove full_name column from users

Revision ID: cbb3c08e0af3
Revises: 1ec408070340
Create Date: 2025-11-25 10:56:00.415060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb3c08e0af3'
down_revision = '1ec408070340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
